"""
Model card schema + Markdown writer for D.R.O.N.A. trained models.

Mirrors data_pipeline.DataCard: every trained model (e.g. the advising LoRA
adapter) gets a model_card.md documenting base model, training data provenance,
hyperparameters, intended use, evaluation, and limitations — the thesis's
evidence of responsible model engineering.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import yaml
from pydantic import BaseModel, Field


class ModelCard(BaseModel):
    name: str
    version: str = "0.1.0"
    created_at: datetime = Field(default_factory=datetime.utcnow)

    base_model: str
    method: str = Field(description="e.g. 'QLoRA (4-bit) + PEFT'")
    task: str = "bias-aware academic/career advising (JSON output)"

    training_data: str = Field(description="What the model was trained on")
    training_data_synthetic: bool = True
    num_train_examples: int | None = None
    num_gold_reviewed: int | None = None
    hyperparameters: dict = Field(default_factory=dict)

    intended_use: str = ""
    out_of_scope: list[str] = Field(default_factory=list)
    evaluation: dict = Field(default_factory=dict)
    known_limitations: list[str] = Field(default_factory=list)
    license: str = "Base model license applies (MIT for Phi-3.5); adapter MIT"
    notes: str = ""

    def write(self, path: Path, also_yaml: bool = True) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.to_markdown(), encoding="utf-8")
        if also_yaml:
            data = self.model_dump(mode="json")
            data["created_at"] = str(data["created_at"])
            with path.with_suffix(".yaml").open("w", encoding="utf-8") as f:
                yaml.safe_dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    def to_markdown(self) -> str:
        def bullets(items: list[str]) -> str:
            return "\n".join(f"- {x}" for x in items) if items else "- (none)"

        def kv(d: dict) -> str:
            return "\n".join(f"- **{k}**: {v}" for k, v in d.items()) if d else "- (pending)"

        return "\n".join(
            [
                f"# Model Card — `{self.name}`",
                "",
                f"**Base model:** {self.base_model}",
                f"**Method:** {self.method}",
                f"**Task:** {self.task}",
                f"**Version:** {self.version}  **Created:** {self.created_at.date()}",
                f"**License:** {self.license}",
                "",
                "## Training data",
                self.training_data,
                f"- synthetic: **{self.training_data_synthetic}**",
                f"- train examples: {self.num_train_examples if self.num_train_examples is not None else 'pending'}",
                f"- human-reviewed gold: {self.num_gold_reviewed if self.num_gold_reviewed is not None else 'pending'}",
                "",
                "## Hyperparameters",
                kv(self.hyperparameters),
                "",
                "## Intended use",
                self.intended_use or "_(see thesis)_",
                "",
                "## Out of scope",
                bullets(self.out_of_scope),
                "",
                "## Evaluation",
                kv(self.evaluation),
                "",
                "## Known limitations",
                bullets(self.known_limitations),
                "",
                "## Notes",
                self.notes or "_(none)_",
                "",
            ]
        )


def build_advising_lora_card(
    hyperparameters: dict, num_train: int | None = None, num_gold: int | None = None
) -> ModelCard:
    """Construct the model card for the advising LoRA adapter."""
    return ModelCard(
        name="phi35-lora-advising",
        base_model="microsoft/Phi-3.5-mini-instruct (Q4_K_M for serving via Ollama)",
        method="QLoRA (4-bit NF4) + PEFT LoRA r=16",
        training_data=(
            "~500 synthetic advising Q&A pairs generated by drona.finetune.qa_generator, "
            "grounded in real O*NET/ESCO pathways, Softwarica modules, and (when provided) "
            "Nepali job postings. ~50 pairs human-reviewed into a gold set. All synthetic "
            "data is labelled and never silently mixed with real data."
        ),
        training_data_synthetic=True,
        num_train_examples=num_train,
        num_gold_reviewed=num_gold,
        hyperparameters=hyperparameters,
        intended_use=(
            "Improve adherence to the bias-aware JSON advising format and Nepal-first "
            "framing when used WITH the RAG pipeline (LoRA+RAG). Not a standalone oracle."
        ),
        out_of_scope=[
            "Use without RAG retrieval context (will hallucinate specifics)",
            "Any non-advising task",
            "Live use of cloud LLMs in the request path (local-only invariant)",
        ],
        evaluation={
            "harness": "drona.finetune.ablation (base+RAG vs LoRA+RAG)",
            "metrics": "pathway_count, grounded_rate, nepal_citation_ratio, hedge_frequency, refusal_rate",
            "status": "to be filled after Colab T4 training run",
        },
        known_limitations=[
            "Trained on synthetic data; gold review mitigates but does not eliminate bias",
            "Phi-3.5-mini capacity limits complex multi-constraint reasoning",
            "Adapter must be merged + re-quantised to GGUF for Ollama serving",
        ],
        notes="Train via notebooks/09_lora_finetune_phi35.ipynb on a Colab T4.",
    )
