"""
ACT training script for D.R.O.N.A. gesture generation — Research Contribution C3.

Trains one ACT (Action Chunking with Transformers) policy per gesture using the
bootstrap demonstration data generated by collect_demonstrations.py.

Prerequisites:
    1. pip install git+https://github.com/huggingface/lerobot.git
    2. python scripts/collect_demonstrations.py  (generates training data)

Usage:
    python scripts/train_act.py
    python scripts/train_act.py --epochs 200 --batch-size 16
    python scripts/train_act.py --gestures greet,farewell --device cuda
    python scripts/train_act.py --demo-dir data/demonstrations --checkpoint-dir data/checkpoints
    python scripts/train_act.py --help

Hardware notes (GTX 1650, 4 GB VRAM):
    Default hyperparameters are tuned for 4 GB. If you run out of VRAM, reduce
    --batch-size to 8 or --chunk-size to 5. Training ~100 epochs per gesture
    takes roughly 5–15 minutes on a GTX 1650.

Output:
    data/checkpoints/<gesture>/   — one directory per gesture in HuggingFace
                                    from_pretrained() format; loaded automatically
                                    by PolicyRouter when present.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

import typer
from loguru import logger

# ── LeRobot availability check ────────────────────────────────────────────────

def _check_lerobot() -> bool:
    try:
        import lerobot  # noqa: F401
        return True
    except ImportError:
        return False


def _require_lerobot() -> None:
    if not _check_lerobot():
        typer.secho(
            "\nLeRobot is not installed.\n\n"
            "Install with:\n"
            "  git clone https://github.com/huggingface/lerobot.git\n"
            "  cd lerobot && pip install -e .\n\n"
            "Then re-run this script.",
            fg=typer.colors.RED,
        )
        raise typer.Exit(1)


def _check_torch_gpu() -> str:
    """Return best available device string."""
    try:
        import torch
        if torch.cuda.is_available():
            name = torch.cuda.get_device_name(0)
            mem = torch.cuda.get_device_properties(0).total_memory / (1024 ** 3)
            logger.info(f"GPU: {name} ({mem:.1f} GB VRAM)")
            return "cuda"
        logger.warning("No CUDA GPU found — training on CPU (will be slow).")
        return "cpu"
    except ImportError:
        logger.error("PyTorch not installed. Run: pip install torch")
        raise typer.Exit(1)


# ── Dataset ───────────────────────────────────────────────────────────────────

def _build_torch_dataset(episodes: list, chunk_size: int):  # type: ignore[return]
    """Build a PyTorch Dataset of (observation, action_chunk) pairs.

    Each sample is:
        obs   : shape (DOF,) — joint positions at frame t
        chunk : shape (chunk_size, DOF) — next chunk_size actions from frame t
    """
    import torch
    from torch.utils.data import Dataset

    class GestureDataset(Dataset):  # type: ignore[misc]
        def __init__(self, episodes: list, chunk_size: int) -> None:
            self.samples: list[tuple] = []
            for ep in episodes:
                frames = ep.frames
                for i in range(len(frames)):
                    obs = frames[i].observation_state  # (DOF,)
                    # Collect chunk_size actions; pad with last action if needed
                    chunk_actions = []
                    for j in range(chunk_size):
                        idx = min(i + j, len(frames) - 1)
                        chunk_actions.append(frames[idx].action)
                    chunk = torch.tensor(
                        [a for a in chunk_actions], dtype=torch.float32
                    )  # (chunk_size, DOF)
                    self.samples.append((
                        torch.tensor(obs, dtype=torch.float32),
                        chunk,
                    ))

        def __len__(self) -> int:
            return len(self.samples)

        def __getitem__(self, idx: int):
            return self.samples[idx]

    return GestureDataset(episodes, chunk_size)


# ── ACT config + model ────────────────────────────────────────────────────────

def _make_act_policy(dof: int, chunk_size: int, dim_model: int, n_heads: int,
                     n_encoder_layers: int, n_decoder_layers: int, dropout: float):
    """Instantiate an ACTPolicy with config appropriate for our 6-DOF arm."""
    try:
        from lerobot.common.policies.act.configuration_act import ACTConfig
        from lerobot.common.policies.act.modeling_act import ACTPolicy
    except ImportError as exc:
        raise RuntimeError(
            "Could not import LeRobot ACT classes. "
            "Make sure LeRobot is installed: pip install -e lerobot/"
        ) from exc

    try:
        # LeRobot ≥ 0.3 API (input_shapes / output_shapes as dict)
        config = ACTConfig(
            input_shapes={"observation.state": [dof]},
            output_shapes={"action": [dof]},
            chunk_size=chunk_size,
            n_obs_steps=1,
            dim_model=dim_model,
            n_heads=n_heads,
            dim_feedforward=dim_model * 4,
            feedforward_dim=dim_model * 4,  # some versions use this name
            n_encoder_layers=n_encoder_layers,
            n_decoder_layers=n_decoder_layers,
            dropout=dropout,
            use_vae=False,   # VAE adds complexity; disable for small dataset
        )
    except TypeError:
        # Older LeRobot API — try positional / simpler config
        try:
            config = ACTConfig(
                state_dim=dof,
                action_dim=dof,
                chunk_size=chunk_size,
                dim_model=dim_model,
                n_heads=n_heads,
                n_encoder_layers=n_encoder_layers,
                n_decoder_layers=n_decoder_layers,
                dropout=dropout,
            )
        except TypeError as exc:
            raise RuntimeError(
                f"ACTConfig API mismatch with installed LeRobot version: {exc}\n"
                "Try: pip install --upgrade git+https://github.com/huggingface/lerobot.git"
            ) from exc

    policy = ACTPolicy(config)
    return policy


# ── Training loop ─────────────────────────────────────────────────────────────

def _train_gesture(
    gesture_label: str,
    episodes: list,
    checkpoint_dir: Path,
    *,
    chunk_size: int,
    epochs: int,
    batch_size: int,
    learning_rate: float,
    dim_model: int,
    n_heads: int,
    n_encoder_layers: int,
    n_decoder_layers: int,
    dropout: float,
    device: str,
) -> dict[str, float]:
    """Train ACT for one gesture. Returns training statistics."""
    import torch
    from torch.utils.data import DataLoader

    from drona.interaction.demonstration import DOF

    dataset = _build_torch_dataset(episodes, chunk_size)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True,
                        drop_last=len(dataset) >= batch_size)

    logger.info(
        f"  Training {gesture_label}: {len(dataset)} samples, "
        f"{len(episodes)} episodes, {epochs} epochs"
    )

    try:
        policy = _make_act_policy(
            dof=DOF,
            chunk_size=chunk_size,
            dim_model=dim_model,
            n_heads=n_heads,
            n_encoder_layers=n_encoder_layers,
            n_decoder_layers=n_decoder_layers,
            dropout=dropout,
        )
    except RuntimeError as exc:
        logger.error(f"  Could not create ACT policy for '{gesture_label}': {exc}")
        return {"error": str(exc)}

    policy = policy.to(device)
    policy.train()

    optimizer = torch.optim.AdamW(
        policy.parameters(), lr=learning_rate, weight_decay=1e-4
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=epochs, eta_min=learning_rate * 0.01
    )

    best_loss = float("inf")
    stats: dict[str, float] = {}

    for epoch in range(1, epochs + 1):
        epoch_loss = 0.0
        n_batches = 0

        for obs_batch, chunk_batch in loader:
            obs_batch = obs_batch.to(device)          # (B, DOF)
            chunk_batch = chunk_batch.to(device)       # (B, chunk_size, DOF)

            optimizer.zero_grad()

            # Build the obs dict LeRobot expects
            obs_dict = {"observation.state": obs_batch}

            try:
                loss_dict = policy.forward(obs_dict, chunk_batch)
                if isinstance(loss_dict, dict):
                    loss = loss_dict.get("loss", sum(loss_dict.values()))
                else:
                    loss = loss_dict
            except (TypeError, AttributeError):
                # Some LeRobot versions have different forward signature
                try:
                    output = policy(obs_dict)
                    # Compute MSE loss on first action in chunk
                    loss = torch.nn.functional.mse_loss(
                        output if output.ndim == 2 else output[:, 0, :],
                        chunk_batch[:, 0, :],
                    )
                except Exception as exc:
                    logger.error(
                        f"  Forward pass failed for '{gesture_label}' (epoch {epoch}): {exc}\n"
                        "  Check LeRobot version compatibility."
                    )
                    return {"error": str(exc)}

            loss.backward()
            torch.nn.utils.clip_grad_norm_(policy.parameters(), max_norm=1.0)
            optimizer.step()

            epoch_loss += loss.item()
            n_batches += 1

        scheduler.step()
        mean_loss = epoch_loss / max(n_batches, 1)

        if mean_loss < best_loss:
            best_loss = mean_loss

        if epoch % max(1, epochs // 10) == 0 or epoch == epochs:
            lr_now = scheduler.get_last_lr()[0]
            typer.echo(
                f"    epoch {epoch:4d}/{epochs}  loss={mean_loss:.5f}  "
                f"best={best_loss:.5f}  lr={lr_now:.2e}"
            )

    # Save checkpoint in HuggingFace format (compatible with from_pretrained)
    policy.eval()
    ckpt_path = checkpoint_dir / gesture_label
    ckpt_path.mkdir(parents=True, exist_ok=True)
    try:
        policy.save_pretrained(str(ckpt_path))
        logger.success(f"  Checkpoint saved: {ckpt_path}")
    except AttributeError:
        # Older LeRobot: use torch.save
        import json as _json
        torch.save(policy.state_dict(), ckpt_path / "pytorch_model.bin")
        _json.dump(
            {"model_type": "act", "state_dim": DOF, "action_dim": DOF,
             "chunk_size": chunk_size, "dim_model": dim_model},
            open(ckpt_path / "config.json", "w"),
        )
        logger.success(f"  Checkpoint saved (state_dict): {ckpt_path}")

    stats["best_loss"] = best_loss
    stats["final_loss"] = mean_loss
    stats["n_samples"] = len(dataset)
    return stats


# ── Jerk comparison helper ────────────────────────────────────────────────────

def _measure_act_jerk(gesture_label: str, checkpoint_dir: Path, device: str) -> float:
    """Roll out the trained ACT policy and measure mean jerk."""
    try:
        import torch
        from drona.evaluation.metrics import jerk_score
        from drona.interaction.act_policy import LeRobotACTPolicy
        from drona.interaction.demonstration import REST_POSE
        from drona.interaction.mujoco_env import StubEnv

        policy = LeRobotACTPolicy(checkpoint_dir / gesture_label, device=device)
        env = StubEnv()
        obs = env.reset()
        policy.reset()

        positions = []
        max_steps = 300
        for _ in range(max_steps):
            action = policy.select_action({"observation.state": obs})
            obs, _ = env.step(action)
            positions.append(obs.copy())

        env.close()
        return jerk_score(positions)
    except Exception as exc:
        logger.warning(f"  Could not measure ACT jerk for '{gesture_label}': {exc}")
        return -1.0


# ── CLI ───────────────────────────────────────────────────────────────────────

app = typer.Typer(name="train-act", help="Train ACT gesture policies for D.R.O.N.A.")


@app.command()
def main(
    demo_dir: Optional[str] = typer.Option(
        None, "--demo-dir", help="Directory with demonstrations.jsonl"
    ),
    checkpoint_dir: Optional[str] = typer.Option(
        None, "--checkpoint-dir", help="Output directory for checkpoints"
    ),
    gestures: str = typer.Option(
        "all", "--gestures", help="Comma-separated gesture names, or 'all'"
    ),
    epochs: int = typer.Option(150, "--epochs", "-e", help="Training epochs per gesture"),
    batch_size: int = typer.Option(32, "--batch-size", "-b", help="Batch size"),
    learning_rate: float = typer.Option(1e-4, "--lr", help="Initial learning rate"),
    chunk_size: int = typer.Option(
        10, "--chunk-size",
        help="ACT action chunk length. Reduce to 5 if VRAM is tight."
    ),
    dim_model: int = typer.Option(
        256, "--dim-model", help="ACT transformer hidden dimension"
    ),
    n_heads: int = typer.Option(4, "--n-heads", help="Transformer attention heads"),
    n_encoder_layers: int = typer.Option(2, "--n-enc", help="Encoder layers"),
    n_decoder_layers: int = typer.Option(2, "--n-dec", help="Decoder layers"),
    dropout: float = typer.Option(0.1, "--dropout", help="Dropout rate"),
    device: Optional[str] = typer.Option(
        None, "--device", help="torch device: cuda / cpu (auto-detected if omitted)"
    ),
    measure_jerk: bool = typer.Option(
        True, "--measure-jerk/--no-measure-jerk",
        help="Roll out trained policy and measure jerk after each gesture"
    ),
    log_level: str = typer.Option("INFO", "--log-level"),
) -> None:
    from drona.utils.logging import setup_logging
    from drona.utils.settings import settings
    setup_logging(log_level)
    settings.ensure_dirs()

    _require_lerobot()

    resolved_device = device or _check_torch_gpu()

    # ── Resolve paths ──────────────────────────────────────────────────────────
    demo_path = Path(demo_dir) if demo_dir else settings.data_dir / "demonstrations"
    ckpt_path = Path(checkpoint_dir) if checkpoint_dir else settings.data_dir / "checkpoints"
    jsonl = demo_path / "demonstrations.jsonl"

    if not jsonl.exists():
        typer.secho(
            f"\nDemonstrations file not found: {jsonl}\n"
            "Run first:  python scripts/collect_demonstrations.py\n",
            fg=typer.colors.RED,
        )
        raise typer.Exit(1)

    # ── Load demonstrations ────────────────────────────────────────────────────
    from drona.interaction.demonstration import DemonstrationDataset, GESTURE_KEYFRAMES

    typer.echo(f"Loading demonstrations from {jsonl} ...")
    ds = DemonstrationDataset.load_jsonl(jsonl)
    typer.echo(
        f"  {ds.total_frames} frames across {len(ds.episodes)} episodes\n"
        f"  Gesture counts: {ds.gesture_counts}\n"
    )

    # ── Gesture selection ──────────────────────────────────────────────────────
    gesture_list = (
        list(GESTURE_KEYFRAMES.keys())
        if gestures.strip().lower() == "all"
        else [g.strip() for g in gestures.split(",")]
    )
    unknown = [g for g in gesture_list if g not in GESTURE_KEYFRAMES]
    if unknown:
        typer.secho(f"Unknown gestures: {unknown}", fg=typer.colors.RED)
        raise typer.Exit(1)

    # Group episodes by gesture
    eps_by_gesture: dict[str, list] = {g: [] for g in gesture_list}
    for ep in ds.episodes:
        if ep.gesture_label in eps_by_gesture:
            eps_by_gesture[ep.gesture_label].append(ep)

    # ── Training ───────────────────────────────────────────────────────────────
    typer.secho("\nACT Training", bold=True)
    typer.echo("─" * 60)
    typer.echo(f"Device        : {resolved_device}")
    typer.echo(f"Epochs        : {epochs}  |  Batch: {batch_size}  |  Chunk: {chunk_size}")
    typer.echo(f"Model dim     : {dim_model}  |  Heads: {n_heads}  |  Enc/Dec: {n_encoder_layers}/{n_decoder_layers}")
    typer.echo(f"Checkpoint dir: {ckpt_path}")
    typer.echo()

    results: dict[str, dict] = {}
    for gesture_label in gesture_list:
        episodes = eps_by_gesture.get(gesture_label, [])
        if not episodes:
            typer.secho(
                f"[{gesture_label}] No episodes found — skipping. "
                "Run collect_demonstrations.py first.",
                fg=typer.colors.YELLOW,
            )
            continue

        typer.secho(f"\n[{gesture_label}]", bold=True)
        stats = _train_gesture(
            gesture_label=gesture_label,
            episodes=episodes,
            checkpoint_dir=ckpt_path,
            chunk_size=chunk_size,
            epochs=epochs,
            batch_size=batch_size,
            learning_rate=learning_rate,
            dim_model=dim_model,
            n_heads=n_heads,
            n_encoder_layers=n_encoder_layers,
            n_decoder_layers=n_decoder_layers,
            dropout=dropout,
            device=resolved_device,
        )
        results[gesture_label] = stats

        if measure_jerk and "error" not in stats:
            act_jerk = _measure_act_jerk(gesture_label, ckpt_path, resolved_device)
            if act_jerk >= 0:
                stats["act_jerk"] = act_jerk
                typer.echo(f"  ACT jerk (post-training): {act_jerk:.4f} rad/s³")

    # ── Summary ────────────────────────────────────────────────────────────────
    typer.secho("\n\nTraining Summary", bold=True)
    typer.echo("─" * 60)

    from drona.evaluation.harness import EvaluationHarness
    try:
        harness = EvaluationHarness()
        c3_keyframe = harness.eval_c3()
        keyframe_jerks = {g: m["jerk"] for g, m in c3_keyframe.per_gesture.items()}
    except Exception:
        keyframe_jerks = {}

    for gesture_label, stats in results.items():
        if "error" in stats:
            typer.secho(f"  {gesture_label:<12} ERROR: {stats['error']}", fg=typer.colors.RED)
            continue

        kf_jerk = keyframe_jerks.get(gesture_label, None)
        act_jerk = stats.get("act_jerk", None)

        parts = [
            f"{gesture_label:<12}",
            f"loss={stats['best_loss']:.5f}",
            f"samples={int(stats['n_samples'])}",
        ]
        if kf_jerk is not None and act_jerk is not None:
            improvement = kf_jerk - act_jerk
            direction = "▼" if improvement > 0 else "▲"
            colour = typer.colors.GREEN if improvement > 0 else typer.colors.YELLOW
            parts.append(
                f"jerk: keyframe={kf_jerk:.3f} → ACT={act_jerk:.3f} "
                f"{direction}{abs(improvement):.3f}"
            )
            typer.secho("  " + "  ".join(parts), fg=colour)
        else:
            typer.echo("  " + "  ".join(parts))

    typer.secho(
        "\nCheckpoints ready. Run evaluation with:\n"
        "  python scripts/run_evaluation.py --c3\n"
        "\nOr start the dashboard:\n"
        "  streamlit run drona/dashboard/app.py",
        fg=typer.colors.CYAN,
    )


if __name__ == "__main__":
    app()
